on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'composer.json'
name: Deploy website on push
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v3
      - name: Composer install in plugins
        uses: "php-actions/composer@v6"
      - name: Sync files
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ${{ secrets.SERVER }}
          user: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
