on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'composer.json'
name: Deploy API to production
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Run Migrations
        run: ssh -o StrictHostKeyChecking=no -o HostKeyAlgorithms=+ssh-rsa -o PubkeyAcceptedAlgorithms=+ssh-rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} -p ${{ secrets.SSH_PORT }} "cd ~/domains/whosetrack.nl/ && php artisan migrate --force"
      - name: Get latest code
        uses: actions/checkout@v3
      - name: Composer install
        uses: "php-actions/composer@v6"
        with:
          args: "--ignore-platform-reqs --optimize-autoloader"
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          exclude: |
            sync-state.py
            **/.git*
            **/.git*/**
          server: ${{ secrets.SERVER }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
